// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.
// This code was generated by google-apis-code-generator 1.6.0

#ifndef  GOOGLE_BIGQUERY_API_BIGQUERY_API_H_
#define  GOOGLE_BIGQUERY_API_BIGQUERY_API_H_

#include "google/bigquery_api/big_query_model_training.h"
#include "google/bigquery_api/bigtable_column.h"
#include "google/bigquery_api/bigtable_column_family.h"
#include "google/bigquery_api/bigtable_options.h"
#include "google/bigquery_api/clustering.h"
#include "google/bigquery_api/csv_options.h"
#include "google/bigquery_api/dataset_reference.h"
#include "google/bigquery_api/table_reference.h"
#include "google/bigquery_api/dataset.h"
#include "google/bigquery_api/dataset_list.h"
#include "google/bigquery_api/destination_table_properties.h"
#include "google/bigquery_api/encryption_configuration.h"
#include "google/bigquery_api/error_proto.h"
#include "google/bigquery_api/explain_query_step.h"
#include "google/bigquery_api/explain_query_stage.h"
#include "google/bigquery_api/google_sheets_options.h"
#include "google/bigquery_api/table_field_schema.h"
#include "google/bigquery_api/table_schema.h"
#include "google/bigquery_api/external_data_configuration.h"
#include "google/bigquery_api/job_reference.h"
#include "google/bigquery_api/table_cell.h"
#include "google/bigquery_api/table_row.h"
#include "google/bigquery_api/get_query_results_response.h"
#include "google/bigquery_api/get_service_account_response.h"
#include "google/bigquery_api/iteration_result.h"
#include "google/bigquery_api/job_configuration_table_copy.h"
#include "google/bigquery_api/job_configuration_extract.h"
#include "google/bigquery_api/range_partitioning.h"
#include "google/bigquery_api/time_partitioning.h"
#include "google/bigquery_api/job_configuration_load.h"
#include "google/bigquery_api/query_parameter_type.h"
#include "google/bigquery_api/query_parameter_value.h"
#include "google/bigquery_api/query_parameter.h"
#include "google/bigquery_api/user_defined_function_resource.h"
#include "google/bigquery_api/job_configuration_query.h"
#include "google/bigquery_api/job_configuration.h"
#include "google/bigquery_api/job_statistics4.h"
#include "google/bigquery_api/job_statistics3.h"
#include "google/bigquery_api/query_timeline_sample.h"
#include "google/bigquery_api/job_statistics2.h"
#include "google/bigquery_api/job_statistics.h"
#include "google/bigquery_api/job_status.h"
#include "google/bigquery_api/job.h"
#include "google/bigquery_api/job_cancel_response.h"
#include "google/bigquery_api/job_list.h"
#include "google/bigquery_api/json_object.h"
#include "google/bigquery_api/materialized_view_definition.h"
#include "google/bigquery_api/training_run.h"
#include "google/bigquery_api/model_definition.h"
#include "google/bigquery_api/project_reference.h"
#include "google/bigquery_api/project_list.h"
#include "google/bigquery_api/query_request.h"
#include "google/bigquery_api/query_response.h"
#include "google/bigquery_api/streamingbuffer.h"
#include "google/bigquery_api/view_definition.h"
#include "google/bigquery_api/table.h"
#include "google/bigquery_api/table_data_insert_all_request.h"
#include "google/bigquery_api/table_data_insert_all_response.h"
#include "google/bigquery_api/table_data_list.h"
#include "google/bigquery_api/table_list.h"

#include "google/bigquery_api/bigquery_service.h"


#endif  // GOOGLE_BIGQUERY_API_BIGQUERY_API_H_
