// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2018-10-08 17:45:39 UTC
//   on: 2019-03-01, 03:01:16 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Generated from:
//   Version: v2
//   Revision: 427
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_BIGQUERY_API_BIGTABLE_OPTIONS_H_
#define  GOOGLE_BIGQUERY_API_BIGTABLE_OPTIONS_H_

#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/bigquery_api/bigtable_column_family.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_bigquery_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class BigtableOptions : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static BigtableOptions* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit BigtableOptions(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit BigtableOptions(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~BigtableOptions();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_bigquery_api::BigtableOptions</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_bigquery_api::BigtableOptions");
  }

  /**
   * Determine if the '<code>columnFamilies</code>' attribute was set.
   *
   * @return true if the '<code>columnFamilies</code>' attribute was set.
   */
  bool has_column_families() const {
    return Storage().isMember("columnFamilies");
  }

  /**
   * Clears the '<code>columnFamilies</code>' attribute.
   */
  void clear_column_families() {
    MutableStorage()->removeMember("columnFamilies");
  }


  /**
   * Get a reference to the value of the '<code>columnFamilies</code>'
   * attribute.
   */
  const client::JsonCppArray<BigtableColumnFamily > get_column_families() const;

  /**
   * Gets a reference to a mutable value of the '<code>columnFamilies</code>'
   * property.
   *
   * [Optional] List of column families to expose in the table schema along with
   * their types. This list restricts the column families that can be referenced
   * in queries and specifies their value types. You can use this list to do
   * type conversions - see the 'type' field for more details. If you leave this
   * list empty, all column families are present in the table schema and their
   * values are read as BYTES. During a query only the column families
   * referenced in that query are read from Bigtable.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<BigtableColumnFamily > mutable_columnFamilies();

  /**
   * Determine if the '<code>ignoreUnspecifiedColumnFamilies</code>' attribute
   * was set.
   *
   * @return true if the '<code>ignoreUnspecifiedColumnFamilies</code>'
   * attribute was set.
   */
  bool has_ignore_unspecified_column_families() const {
    return Storage().isMember("ignoreUnspecifiedColumnFamilies");
  }

  /**
   * Clears the '<code>ignoreUnspecifiedColumnFamilies</code>' attribute.
   */
  void clear_ignore_unspecified_column_families() {
    MutableStorage()->removeMember("ignoreUnspecifiedColumnFamilies");
  }


  /**
   * Get the value of the '<code>ignoreUnspecifiedColumnFamilies</code>'
   * attribute.
   */
  bool get_ignore_unspecified_column_families() const {
    const Json::Value& storage = Storage("ignoreUnspecifiedColumnFamilies");
    return client::JsonValueToCppValueHelper<bool >(storage);
  }

  /**
   * Change the '<code>ignoreUnspecifiedColumnFamilies</code>' attribute.
   *
   * [Optional] If field is true, then the column families that are not
   * specified in columnFamilies list are not exposed in the table schema.
   * Otherwise, they are read with BYTES type values. The default value is
   * false.
   *
   * @param[in] value The new value.
   */
  void set_ignore_unspecified_column_families(bool value) {
    client::SetJsonValueFromCppValueHelper<bool >(
      value, MutableStorage("ignoreUnspecifiedColumnFamilies"));
  }

  /**
   * Determine if the '<code>readRowkeyAsString</code>' attribute was set.
   *
   * @return true if the '<code>readRowkeyAsString</code>' attribute was set.
   */
  bool has_read_rowkey_as_string() const {
    return Storage().isMember("readRowkeyAsString");
  }

  /**
   * Clears the '<code>readRowkeyAsString</code>' attribute.
   */
  void clear_read_rowkey_as_string() {
    MutableStorage()->removeMember("readRowkeyAsString");
  }


  /**
   * Get the value of the '<code>readRowkeyAsString</code>' attribute.
   */
  bool get_read_rowkey_as_string() const {
    const Json::Value& storage = Storage("readRowkeyAsString");
    return client::JsonValueToCppValueHelper<bool >(storage);
  }

  /**
   * Change the '<code>readRowkeyAsString</code>' attribute.
   *
   * [Optional] If field is true, then the rowkey column families will be read
   * and converted to string. Otherwise they are read with BYTES type values and
   * users need to manually cast them with CAST if necessary. The default value
   * is false.
   *
   * @param[in] value The new value.
   */
  void set_read_rowkey_as_string(bool value) {
    client::SetJsonValueFromCppValueHelper<bool >(
      value, MutableStorage("readRowkeyAsString"));
  }

 private:
  void operator=(const BigtableOptions&);
};  // BigtableOptions
}  // namespace google_bigquery_api
#endif  // GOOGLE_BIGQUERY_API_BIGTABLE_OPTIONS_H_
