// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.6.0

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google API Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Generated from:
//   Version: v2
//   Revision: 20190224
// Generated by:
//    Tool: google-apis-code-generator 1.6.0
//     C++: 0.1.5
#ifndef  GOOGLE_BIGQUERY_API_ENCRYPTION_CONFIGURATION_H_
#define  GOOGLE_BIGQUERY_API_ENCRYPTION_CONFIGURATION_H_

#include <string>

#include "googleapis/client/data/jsoncpp_data.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_bigquery_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class EncryptionConfiguration : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static EncryptionConfiguration* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit EncryptionConfiguration(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit EncryptionConfiguration(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~EncryptionConfiguration();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_bigquery_api::EncryptionConfiguration</code>
   */
  const char* GetTypeName() const {
    return "google_bigquery_api::EncryptionConfiguration";
  }

  /**
   * Determine if the '<code>kmsKeyName</code>' attribute was set.
   *
   * @return true if the '<code>kmsKeyName</code>' attribute was set.
   */
  bool has_kms_key_name() const {
    return Storage().isMember("kmsKeyName");
  }

  /**
   * Clears the '<code>kmsKeyName</code>' attribute.
   */
  void clear_kms_key_name() {
    MutableStorage()->removeMember("kmsKeyName");
  }


  /**
   * Get the value of the '<code>kmsKeyName</code>' attribute.
   */
  const std::string get_kms_key_name() const {
    const Json::Value& v = Storage("kmsKeyName");
    if (v == Json::Value::null) return std::string("");
    return std::string(v.asCString());
  }

  /**
   * Change the '<code>kmsKeyName</code>' attribute.
   *
   * [Optional] Describes the Cloud KMS encryption key that will be used to
   * protect destination BigQuery table. The BigQuery Service Account associated
   * with your project requires access to this encryption key.
   *
   * @param[in] value The new value.
   */
  void set_kms_key_name(const std::string& value) {
    *MutableStorage("kmsKeyName") = value.data();
  }

 private:
  void operator=(const EncryptionConfiguration&);
};  // EncryptionConfiguration
}  // namespace google_bigquery_api
#endif  // GOOGLE_BIGQUERY_API_ENCRYPTION_CONFIGURATION_H_
