// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.6.0

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google API Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Description:
//   A data platform for customers to create, manage, share and query data.
// Classes:
//   ExternalDataConfiguration
// Documentation:
//   https://cloud.google.com/bigquery/

#include "google/bigquery_api/external_data_configuration.h"

#include <string>

#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/client/data/jsoncpp_data.h"

#include "google/bigquery_api/bigtable_options.h"
#include "google/bigquery_api/csv_options.h"
#include "google/bigquery_api/google_sheets_options.h"
#include "google/bigquery_api/table_schema.h"


#include "absl/strings/str_cat.h"


namespace google_bigquery_api {
using namespace googleapis;


// Object factory method (static).
ExternalDataConfiguration* ExternalDataConfiguration::New() {
  return new client::JsonCppCapsule<ExternalDataConfiguration>;
}

// Standard immutable constructor.
ExternalDataConfiguration::ExternalDataConfiguration(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
ExternalDataConfiguration::ExternalDataConfiguration(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
ExternalDataConfiguration::~ExternalDataConfiguration() {
}

// Properties.

const BigtableOptions ExternalDataConfiguration::get_bigtable_options() const {
   const Json::Value& storage = Storage("bigtableOptions");
   return client::JsonValueToCppValueHelper<BigtableOptions >(storage);
}

BigtableOptions ExternalDataConfiguration::mutable_bigtableOptions() {
  Json::Value* storage = MutableStorage("bigtableOptions");
  return client::JsonValueToMutableCppValueHelper<BigtableOptions >(storage);
}

const CsvOptions ExternalDataConfiguration::get_csv_options() const {
   const Json::Value& storage = Storage("csvOptions");
   return client::JsonValueToCppValueHelper<CsvOptions >(storage);
}

CsvOptions ExternalDataConfiguration::mutable_csvOptions() {
  Json::Value* storage = MutableStorage("csvOptions");
  return client::JsonValueToMutableCppValueHelper<CsvOptions >(storage);
}

const GoogleSheetsOptions ExternalDataConfiguration::get_google_sheets_options() const {
   const Json::Value& storage = Storage("googleSheetsOptions");
   return client::JsonValueToCppValueHelper<GoogleSheetsOptions >(storage);
}

GoogleSheetsOptions ExternalDataConfiguration::mutable_googleSheetsOptions() {
  Json::Value* storage = MutableStorage("googleSheetsOptions");
  return client::JsonValueToMutableCppValueHelper<GoogleSheetsOptions >(storage);
}

const TableSchema ExternalDataConfiguration::get_schema() const {
   const Json::Value& storage = Storage("schema");
   return client::JsonValueToCppValueHelper<TableSchema >(storage);
}

TableSchema ExternalDataConfiguration::mutable_schema() {
  Json::Value* storage = MutableStorage("schema");
  return client::JsonValueToMutableCppValueHelper<TableSchema >(storage);
}
}  // namespace google_bigquery_api
