// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.6.0

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google API Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Generated from:
//   Version: v2
//   Revision: 20190224
// Generated by:
//    Tool: google-apis-code-generator 1.6.0
//     C++: 0.1.5
#ifndef  GOOGLE_BIGQUERY_API_JOB_CANCEL_RESPONSE_H_
#define  GOOGLE_BIGQUERY_API_JOB_CANCEL_RESPONSE_H_

#include <string>
#include "googleapis/client/data/jsoncpp_data.h"

#include "google/bigquery_api/job.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_bigquery_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class JobCancelResponse : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static JobCancelResponse* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit JobCancelResponse(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit JobCancelResponse(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~JobCancelResponse();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_bigquery_api::JobCancelResponse</code>
   */
  const char* GetTypeName() const {
    return "google_bigquery_api::JobCancelResponse";
  }

  /**
   * Determine if the '<code>job</code>' attribute was set.
   *
   * @return true if the '<code>job</code>' attribute was set.
   */
  bool has_job() const {
    return Storage().isMember("job");
  }

  /**
   * Clears the '<code>job</code>' attribute.
   */
  void clear_job() {
    MutableStorage()->removeMember("job");
  }


  /**
   * Get a reference to the value of the '<code>job</code>' attribute.
   */
  const Job get_job() const;

  /**
   * Gets a reference to a mutable value of the '<code>job</code>' property.
   *
   * The final state of the job.
   *
   * @return The result can be modified to change the attribute value.
   */
  Job mutable_job();

  /**
   * Determine if the '<code>kind</code>' attribute was set.
   *
   * @return true if the '<code>kind</code>' attribute was set.
   */
  bool has_kind() const {
    return Storage().isMember("kind");
  }

  /**
   * Clears the '<code>kind</code>' attribute.
   */
  void clear_kind() {
    MutableStorage()->removeMember("kind");
  }


  /**
   * Get the value of the '<code>kind</code>' attribute.
   */
  const std::string get_kind() const {
    const Json::Value& v = Storage("kind");
    if (v == Json::Value::null) return std::string("");
    return std::string(v.asCString());
  }

  /**
   * Change the '<code>kind</code>' attribute.
   *
   * The resource type of the response.
   *
   * @param[in] value The new value.
   */
  void set_kind(const std::string& value) {
    *MutableStorage("kind") = value.data();
  }

 private:
  void operator=(const JobCancelResponse&);
};  // JobCancelResponse
}  // namespace google_bigquery_api
#endif  // GOOGLE_BIGQUERY_API_JOB_CANCEL_RESPONSE_H_
