// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2018-10-08 17:45:39 UTC
//   on: 2019-03-01, 03:01:16 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Generated from:
//   Version: v2
//   Revision: 427
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_BIGQUERY_API_JOB_REFERENCE_H_
#define  GOOGLE_BIGQUERY_API_JOB_REFERENCE_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_bigquery_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class JobReference : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static JobReference* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit JobReference(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit JobReference(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~JobReference();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_bigquery_api::JobReference</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_bigquery_api::JobReference");
  }

  /**
   * Determine if the '<code>jobId</code>' attribute was set.
   *
   * @return true if the '<code>jobId</code>' attribute was set.
   */
  bool has_job_id() const {
    return Storage().isMember("jobId");
  }

  /**
   * Clears the '<code>jobId</code>' attribute.
   */
  void clear_job_id() {
    MutableStorage()->removeMember("jobId");
  }


  /**
   * Get the value of the '<code>jobId</code>' attribute.
   */
  const StringPiece get_job_id() const {
    const Json::Value& v = Storage("jobId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>jobId</code>' attribute.
   *
   * [Required] The ID of the job. The ID must contain only letters (a-z, A-Z),
   * numbers (0-9), underscores (_), or dashes (-). The maximum length is 1,024
   * characters.
   *
   * @param[in] value The new value.
   */
  void set_job_id(const StringPiece& value) {
    *MutableStorage("jobId") = value.data();
  }

  /**
   * Determine if the '<code>location</code>' attribute was set.
   *
   * @return true if the '<code>location</code>' attribute was set.
   */
  bool has_location() const {
    return Storage().isMember("location");
  }

  /**
   * Clears the '<code>location</code>' attribute.
   */
  void clear_location() {
    MutableStorage()->removeMember("location");
  }


  /**
   * Get the value of the '<code>location</code>' attribute.
   */
  const StringPiece get_location() const {
    const Json::Value& v = Storage("location");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>location</code>' attribute.
   *
   * The geographic location of the job. See details at
   * https://cloud.google.com/bigquery/docs/locations#specifying_your_location.
   *
   * @param[in] value The new value.
   */
  void set_location(const StringPiece& value) {
    *MutableStorage("location") = value.data();
  }

  /**
   * Determine if the '<code>projectId</code>' attribute was set.
   *
   * @return true if the '<code>projectId</code>' attribute was set.
   */
  bool has_project_id() const {
    return Storage().isMember("projectId");
  }

  /**
   * Clears the '<code>projectId</code>' attribute.
   */
  void clear_project_id() {
    MutableStorage()->removeMember("projectId");
  }


  /**
   * Get the value of the '<code>projectId</code>' attribute.
   */
  const StringPiece get_project_id() const {
    const Json::Value& v = Storage("projectId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>projectId</code>' attribute.
   *
   * [Required] The ID of the project containing this job.
   *
   * @param[in] value The new value.
   */
  void set_project_id(const StringPiece& value) {
    *MutableStorage("projectId") = value.data();
  }

 private:
  void operator=(const JobReference&);
};  // JobReference
}  // namespace google_bigquery_api
#endif  // GOOGLE_BIGQUERY_API_JOB_REFERENCE_H_
