// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.6.0

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google API Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Description:
//   A data platform for customers to create, manage, share and query data.
// Classes:
//   JobConfigurationTableCopy
// Documentation:
//   https://cloud.google.com/bigquery/

#include "google/bigquery_api/job_configuration_table_copy.h"

#include <string>

#include <string>
#include "googleapis/client/data/jsoncpp_data.h"

#include "google/bigquery_api/encryption_configuration.h"
#include "google/bigquery_api/table_reference.h"


#include "absl/strings/str_cat.h"


namespace google_bigquery_api {
using namespace googleapis;


// Object factory method (static).
JobConfigurationTableCopy* JobConfigurationTableCopy::New() {
  return new client::JsonCppCapsule<JobConfigurationTableCopy>;
}

// Standard immutable constructor.
JobConfigurationTableCopy::JobConfigurationTableCopy(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
JobConfigurationTableCopy::JobConfigurationTableCopy(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
JobConfigurationTableCopy::~JobConfigurationTableCopy() {
}

// Properties.

const EncryptionConfiguration JobConfigurationTableCopy::get_destination_encryption_configuration() const {
   const Json::Value& storage = Storage("destinationEncryptionConfiguration");
   return client::JsonValueToCppValueHelper<EncryptionConfiguration >(storage);
}

EncryptionConfiguration JobConfigurationTableCopy::mutable_destinationEncryptionConfiguration() {
  Json::Value* storage = MutableStorage("destinationEncryptionConfiguration");
  return client::JsonValueToMutableCppValueHelper<EncryptionConfiguration >(storage);
}

const TableReference JobConfigurationTableCopy::get_destination_table() const {
   const Json::Value& storage = Storage("destinationTable");
   return client::JsonValueToCppValueHelper<TableReference >(storage);
}

TableReference JobConfigurationTableCopy::mutable_destinationTable() {
  Json::Value* storage = MutableStorage("destinationTable");
  return client::JsonValueToMutableCppValueHelper<TableReference >(storage);
}

const TableReference JobConfigurationTableCopy::get_source_table() const {
   const Json::Value& storage = Storage("sourceTable");
   return client::JsonValueToCppValueHelper<TableReference >(storage);
}

TableReference JobConfigurationTableCopy::mutable_sourceTable() {
  Json::Value* storage = MutableStorage("sourceTable");
  return client::JsonValueToMutableCppValueHelper<TableReference >(storage);
}

const client::JsonCppArray<TableReference > JobConfigurationTableCopy::get_source_tables() const {
   const Json::Value& storage = Storage("sourceTables");
   return client::JsonValueToCppValueHelper<client::JsonCppArray<TableReference > >(storage);
}

client::JsonCppArray<TableReference > JobConfigurationTableCopy::mutable_sourceTables() {
  Json::Value* storage = MutableStorage("sourceTables");
  return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<TableReference > >(storage);
}
}  // namespace google_bigquery_api
