// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.6.0

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google API Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Generated from:
//   Version: v2
//   Revision: 20190224
// Generated by:
//    Tool: google-apis-code-generator 1.6.0
//     C++: 0.1.5
#ifndef  GOOGLE_BIGQUERY_API_JOB_STATUS_H_
#define  GOOGLE_BIGQUERY_API_JOB_STATUS_H_

#include <string>
#include "googleapis/client/data/jsoncpp_data.h"

#include "google/bigquery_api/error_proto.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_bigquery_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class JobStatus : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static JobStatus* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit JobStatus(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit JobStatus(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~JobStatus();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_bigquery_api::JobStatus</code>
   */
  const char* GetTypeName() const {
    return "google_bigquery_api::JobStatus";
  }

  /**
   * Determine if the '<code>errorResult</code>' attribute was set.
   *
   * @return true if the '<code>errorResult</code>' attribute was set.
   */
  bool has_error_result() const {
    return Storage().isMember("errorResult");
  }

  /**
   * Clears the '<code>errorResult</code>' attribute.
   */
  void clear_error_result() {
    MutableStorage()->removeMember("errorResult");
  }


  /**
   * Get a reference to the value of the '<code>errorResult</code>' attribute.
   */
  const ErrorProto get_error_result() const;

  /**
   * Gets a reference to a mutable value of the '<code>errorResult</code>'
   * property.
   *
   * [Output-only] Final error result of the job. If present, indicates that the
   * job has completed and was unsuccessful.
   *
   * @return The result can be modified to change the attribute value.
   */
  ErrorProto mutable_errorResult();

  /**
   * Determine if the '<code>errors</code>' attribute was set.
   *
   * @return true if the '<code>errors</code>' attribute was set.
   */
  bool has_errors() const {
    return Storage().isMember("errors");
  }

  /**
   * Clears the '<code>errors</code>' attribute.
   */
  void clear_errors() {
    MutableStorage()->removeMember("errors");
  }


  /**
   * Get a reference to the value of the '<code>errors</code>' attribute.
   */
  const client::JsonCppArray<ErrorProto > get_errors() const;

  /**
   * Gets a reference to a mutable value of the '<code>errors</code>' property.
   *
   * [Output-only] The first errors encountered during the running of the job.
   * The final message includes the number of errors that caused the process to
   * stop. Errors here do not necessarily mean that the job has completed or was
   * unsuccessful.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<ErrorProto > mutable_errors();

  /**
   * Determine if the '<code>state</code>' attribute was set.
   *
   * @return true if the '<code>state</code>' attribute was set.
   */
  bool has_state() const {
    return Storage().isMember("state");
  }

  /**
   * Clears the '<code>state</code>' attribute.
   */
  void clear_state() {
    MutableStorage()->removeMember("state");
  }


  /**
   * Get the value of the '<code>state</code>' attribute.
   */
  const std::string get_state() const {
    const Json::Value& v = Storage("state");
    if (v == Json::Value::null) return std::string("");
    return std::string(v.asCString());
  }

  /**
   * Change the '<code>state</code>' attribute.
   *
   * [Output-only] Running state of the job.
   *
   * @param[in] value The new value.
   */
  void set_state(const std::string& value) {
    *MutableStorage("state") = value.data();
  }

 private:
  void operator=(const JobStatus&);
};  // JobStatus
}  // namespace google_bigquery_api
#endif  // GOOGLE_BIGQUERY_API_JOB_STATUS_H_
