// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.6.0

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google API Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Description:
//   A data platform for customers to create, manage, share and query data.
// Classes:
//   JobConfiguration
// Documentation:
//   https://cloud.google.com/bigquery/

#include "google/bigquery_api/job_configuration.h"

#include <string>

#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/client/data/jsoncpp_data.h"

#include "google/bigquery_api/job_configuration_extract.h"
#include "google/bigquery_api/job_configuration_load.h"
#include "google/bigquery_api/job_configuration_query.h"
#include "google/bigquery_api/job_configuration_table_copy.h"


#include "absl/strings/str_cat.h"


namespace google_bigquery_api {
using namespace googleapis;


// Object factory method (static).
JobConfiguration* JobConfiguration::New() {
  return new client::JsonCppCapsule<JobConfiguration>;
}

// Standard immutable constructor.
JobConfiguration::JobConfiguration(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
JobConfiguration::JobConfiguration(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
JobConfiguration::~JobConfiguration() {
}

// Properties.

const JobConfigurationTableCopy JobConfiguration::get_copy() const {
   const Json::Value& storage = Storage("copy");
   return client::JsonValueToCppValueHelper<JobConfigurationTableCopy >(storage);
}

JobConfigurationTableCopy JobConfiguration::mutable_copy() {
  Json::Value* storage = MutableStorage("copy");
  return client::JsonValueToMutableCppValueHelper<JobConfigurationTableCopy >(storage);
}

const JobConfigurationExtract JobConfiguration::get_extract() const {
   const Json::Value& storage = Storage("extract");
   return client::JsonValueToCppValueHelper<JobConfigurationExtract >(storage);
}

JobConfigurationExtract JobConfiguration::mutable_extract() {
  Json::Value* storage = MutableStorage("extract");
  return client::JsonValueToMutableCppValueHelper<JobConfigurationExtract >(storage);
}

const JobConfigurationLoad JobConfiguration::get_load() const {
   const Json::Value& storage = Storage("load");
   return client::JsonValueToCppValueHelper<JobConfigurationLoad >(storage);
}

JobConfigurationLoad JobConfiguration::mutable_load() {
  Json::Value* storage = MutableStorage("load");
  return client::JsonValueToMutableCppValueHelper<JobConfigurationLoad >(storage);
}

const JobConfigurationQuery JobConfiguration::get_query() const {
   const Json::Value& storage = Storage("query");
   return client::JsonValueToCppValueHelper<JobConfigurationQuery >(storage);
}

JobConfigurationQuery JobConfiguration::mutable_query() {
  Json::Value* storage = MutableStorage("query");
  return client::JsonValueToMutableCppValueHelper<JobConfigurationQuery >(storage);
}
}  // namespace google_bigquery_api
