// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.6.0

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google API Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Description:
//   A data platform for customers to create, manage, share and query data.
// Classes:
//   JobStatistics
// Documentation:
//   https://cloud.google.com/bigquery/

#include "google/bigquery_api/job_statistics.h"

#include <string>

#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/client/data/jsoncpp_data.h"

#include "google/bigquery_api/job_statistics2.h"
#include "google/bigquery_api/job_statistics3.h"
#include "google/bigquery_api/job_statistics4.h"


#include "absl/strings/str_cat.h"


namespace google_bigquery_api {
using namespace googleapis;



// Object factory method (static).
JobStatistics::JobStatisticsReservationUsage* JobStatistics::JobStatisticsReservationUsage::New() {
  return new client::JsonCppCapsule<JobStatisticsReservationUsage>;
}

// Standard immutable constructor.
JobStatistics::JobStatisticsReservationUsage::JobStatisticsReservationUsage(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
JobStatistics::JobStatisticsReservationUsage::JobStatisticsReservationUsage(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
JobStatistics::JobStatisticsReservationUsage::~JobStatisticsReservationUsage() {
}

// Properties.
// Object factory method (static).
JobStatistics* JobStatistics::New() {
  return new client::JsonCppCapsule<JobStatistics>;
}

// Standard immutable constructor.
JobStatistics::JobStatistics(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
JobStatistics::JobStatistics(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
JobStatistics::~JobStatistics() {
}

// Properties.

const JobStatistics4 JobStatistics::get_extract() const {
   const Json::Value& storage = Storage("extract");
   return client::JsonValueToCppValueHelper<JobStatistics4 >(storage);
}

JobStatistics4 JobStatistics::mutable_extract() {
  Json::Value* storage = MutableStorage("extract");
  return client::JsonValueToMutableCppValueHelper<JobStatistics4 >(storage);
}

const JobStatistics3 JobStatistics::get_load() const {
   const Json::Value& storage = Storage("load");
   return client::JsonValueToCppValueHelper<JobStatistics3 >(storage);
}

JobStatistics3 JobStatistics::mutable_load() {
  Json::Value* storage = MutableStorage("load");
  return client::JsonValueToMutableCppValueHelper<JobStatistics3 >(storage);
}

const JobStatistics2 JobStatistics::get_query() const {
   const Json::Value& storage = Storage("query");
   return client::JsonValueToCppValueHelper<JobStatistics2 >(storage);
}

JobStatistics2 JobStatistics::mutable_query() {
  Json::Value* storage = MutableStorage("query");
  return client::JsonValueToMutableCppValueHelper<JobStatistics2 >(storage);
}
}  // namespace google_bigquery_api
