// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.6.0

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google API Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Generated from:
//   Version: v2
//   Revision: 20190224
// Generated by:
//    Tool: google-apis-code-generator 1.6.0
//     C++: 0.1.5
#ifndef  GOOGLE_BIGQUERY_API_MATERIALIZED_VIEW_DEFINITION_H_
#define  GOOGLE_BIGQUERY_API_MATERIALIZED_VIEW_DEFINITION_H_

#include <string>

#include "googleapis/base/integral_types.h"
#include "googleapis/client/data/jsoncpp_data.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_bigquery_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class MaterializedViewDefinition : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static MaterializedViewDefinition* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit MaterializedViewDefinition(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit MaterializedViewDefinition(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~MaterializedViewDefinition();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_bigquery_api::MaterializedViewDefinition</code>
   */
  const char* GetTypeName() const {
    return "google_bigquery_api::MaterializedViewDefinition";
  }

  /**
   * Determine if the '<code>lastRefreshTime</code>' attribute was set.
   *
   * @return true if the '<code>lastRefreshTime</code>' attribute was set.
   */
  bool has_last_refresh_time() const {
    return Storage().isMember("lastRefreshTime");
  }

  /**
   * Clears the '<code>lastRefreshTime</code>' attribute.
   */
  void clear_last_refresh_time() {
    MutableStorage()->removeMember("lastRefreshTime");
  }


  /**
   * Get the value of the '<code>lastRefreshTime</code>' attribute.
   */
  int64 get_last_refresh_time() const {
    const Json::Value& storage = Storage("lastRefreshTime");
    return client::JsonValueToCppValueHelper<int64 >(storage);
  }

  /**
   * Change the '<code>lastRefreshTime</code>' attribute.
   *
   * [Output-only] [TrustedTester] The time when this materialized view was last
   * modified, in milliseconds since the epoch.
   *
   * @param[in] value The new value.
   */
  void set_last_refresh_time(int64 value) {
    client::SetJsonValueFromCppValueHelper<int64 >(
      value, MutableStorage("lastRefreshTime"));
  }

  /**
   * Determine if the '<code>query</code>' attribute was set.
   *
   * @return true if the '<code>query</code>' attribute was set.
   */
  bool has_query() const {
    return Storage().isMember("query");
  }

  /**
   * Clears the '<code>query</code>' attribute.
   */
  void clear_query() {
    MutableStorage()->removeMember("query");
  }


  /**
   * Get the value of the '<code>query</code>' attribute.
   */
  const std::string get_query() const {
    const Json::Value& v = Storage("query");
    if (v == Json::Value::null) return std::string("");
    return std::string(v.asCString());
  }

  /**
   * Change the '<code>query</code>' attribute.
   *
   * [Required] A query whose result is persisted.
   *
   * @param[in] value The new value.
   */
  void set_query(const std::string& value) {
    *MutableStorage("query") = value.data();
  }

 private:
  void operator=(const MaterializedViewDefinition&);
};  // MaterializedViewDefinition
}  // namespace google_bigquery_api
#endif  // GOOGLE_BIGQUERY_API_MATERIALIZED_VIEW_DEFINITION_H_
