// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.6.0

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google API Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Description:
//   A data platform for customers to create, manage, share and query data.
// Classes:
//   ModelDefinition
// Documentation:
//   https://cloud.google.com/bigquery/

#include "google/bigquery_api/model_definition.h"

#include <string>

#include <string>
#include "googleapis/client/data/jsoncpp_data.h"

#include "google/bigquery_api/training_run.h"


#include "absl/strings/str_cat.h"


namespace google_bigquery_api {
using namespace googleapis;



// Object factory method (static).
ModelDefinition::ModelDefinitionModelOptions* ModelDefinition::ModelDefinitionModelOptions::New() {
  return new client::JsonCppCapsule<ModelDefinitionModelOptions>;
}

// Standard immutable constructor.
ModelDefinition::ModelDefinitionModelOptions::ModelDefinitionModelOptions(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
ModelDefinition::ModelDefinitionModelOptions::ModelDefinitionModelOptions(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
ModelDefinition::ModelDefinitionModelOptions::~ModelDefinitionModelOptions() {
}

// Properties.
// Object factory method (static).
ModelDefinition* ModelDefinition::New() {
  return new client::JsonCppCapsule<ModelDefinition>;
}

// Standard immutable constructor.
ModelDefinition::ModelDefinition(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
ModelDefinition::ModelDefinition(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
ModelDefinition::~ModelDefinition() {
}

// Properties.

const client::JsonCppArray<TrainingRun > ModelDefinition::get_training_runs() const {
   const Json::Value& storage = Storage("trainingRuns");
   return client::JsonValueToCppValueHelper<client::JsonCppArray<TrainingRun > >(storage);
}

client::JsonCppArray<TrainingRun > ModelDefinition::mutable_trainingRuns() {
  Json::Value* storage = MutableStorage("trainingRuns");
  return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<TrainingRun > >(storage);
}
}  // namespace google_bigquery_api
