// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.6.0

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google API Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Description:
//   A data platform for customers to create, manage, share and query data.
// Classes:
//   QueryParameterType
// Documentation:
//   https://cloud.google.com/bigquery/

#include "google/bigquery_api/query_parameter_type.h"

#include <string>

#include <string>
#include "googleapis/client/data/jsoncpp_data.h"

#include "google/bigquery_api/query_parameter_type.h"


#include "absl/strings/str_cat.h"


namespace google_bigquery_api {
using namespace googleapis;



// Object factory method (static).
QueryParameterType::QueryParameterTypeStructTypes* QueryParameterType::QueryParameterTypeStructTypes::New() {
  return new client::JsonCppCapsule<QueryParameterTypeStructTypes>;
}

// Standard immutable constructor.
QueryParameterType::QueryParameterTypeStructTypes::QueryParameterTypeStructTypes(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
QueryParameterType::QueryParameterTypeStructTypes::QueryParameterTypeStructTypes(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
QueryParameterType::QueryParameterTypeStructTypes::~QueryParameterTypeStructTypes() {
}

// Properties.

const QueryParameterType QueryParameterType::QueryParameterTypeStructTypes::get_type() const {
   const Json::Value& storage = Storage("type");
   return client::JsonValueToCppValueHelper<QueryParameterType >(storage);
}

QueryParameterType QueryParameterType::QueryParameterTypeStructTypes::mutable_type() {
  Json::Value* storage = MutableStorage("type");
  return client::JsonValueToMutableCppValueHelper<QueryParameterType >(storage);
}
// Object factory method (static).
QueryParameterType* QueryParameterType::New() {
  return new client::JsonCppCapsule<QueryParameterType>;
}

// Standard immutable constructor.
QueryParameterType::QueryParameterType(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
QueryParameterType::QueryParameterType(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
QueryParameterType::~QueryParameterType() {
}

// Properties.

const QueryParameterType QueryParameterType::get_array_type() const {
   const Json::Value& storage = Storage("arrayType");
   return client::JsonValueToCppValueHelper<QueryParameterType >(storage);
}

QueryParameterType QueryParameterType::mutable_arrayType() {
  Json::Value* storage = MutableStorage("arrayType");
  return client::JsonValueToMutableCppValueHelper<QueryParameterType >(storage);
}
}  // namespace google_bigquery_api
