// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.6.0

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google API Discovery Service.
// Service:
//   BigQuery API (bigquery/v2)
// Description:
//   A data platform for customers to create, manage, share and query data.
// Classes:
//   QueryParameterValue
// Documentation:
//   https://cloud.google.com/bigquery/

#include "google/bigquery_api/query_parameter_value.h"

#include <string>

#include <string>
#include "googleapis/client/data/jsoncpp_data.h"

#include "google/bigquery_api/query_parameter_value.h"


#include "absl/strings/str_cat.h"


namespace google_bigquery_api {
using namespace googleapis;


// Object factory method (static).
QueryParameterValue* QueryParameterValue::New() {
  return new client::JsonCppCapsule<QueryParameterValue>;
}

// Standard immutable constructor.
QueryParameterValue::QueryParameterValue(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
QueryParameterValue::QueryParameterValue(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
QueryParameterValue::~QueryParameterValue() {
}

// Properties.

const client::JsonCppArray<QueryParameterValue > QueryParameterValue::get_array_values() const {
   const Json::Value& storage = Storage("arrayValues");
   return client::JsonValueToCppValueHelper<client::JsonCppArray<QueryParameterValue > >(storage);
}

client::JsonCppArray<QueryParameterValue > QueryParameterValue::mutable_arrayValues() {
  Json::Value* storage = MutableStorage("arrayValues");
  return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<QueryParameterValue > >(storage);
}

const client::JsonCppAssociativeArray<QueryParameterValue > QueryParameterValue::get_struct_values() const {
   const Json::Value& storage = Storage("structValues");
   return client::JsonValueToCppValueHelper<client::JsonCppAssociativeArray<QueryParameterValue > >(storage);
}

client::JsonCppAssociativeArray<QueryParameterValue > QueryParameterValue::mutable_structValues() {
  Json::Value* storage = MutableStorage("structValues");
  return client::JsonValueToMutableCppValueHelper<client::JsonCppAssociativeArray<QueryParameterValue > >(storage);
}
}  // namespace google_bigquery_api
